# 📖 Simple document generation tool! Dependence Node.js run.
# https://github.com/jaywcjlove/idoc

name: idoc
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Create idoc config.
        run: |
          cat > idoc.yml << EOF
          site: hf-model-downloader
          description: A cross-platform GUI application for easily downloading Hugging Face models without requiring technical knowledge or setup.
          keywords: Hugging Face,Model Downloader,GUI Application,Cross-Platform,Easy Download,Hugging Face Models
          favicon: assets/icon.ico
          logo: assets/icon.png

          openSource: https://github.com/samzong/hf-model-downloader

          tocs: false

          element:
            wrapper: style=max-width:720px;

          menus:
            Home: index.html
            About:
              url: https://github.com/samzong
              target: __blank
          
          cacheFileStat: true

          footer: |
            Copyright © {{idocYear}} <a href="https://github.com/samzong" target="_blank">samzong</a><br />
            <script>
            function downloadLatest() {
              const platform = navigator.platform.toLowerCase();
              const userAgent = navigator.userAgent.toLowerCase();
              
              let downloadUrl = '';
              
              if (platform.includes('mac')) {
                // macOS
                if (userAgent.includes('arm') || userAgent.includes('apple')) {
                  downloadUrl = 'https://github.com/samzong/hf-model-downloader/releases/latest/download/hf-model-downloader-arm64.dmg';
                } else {
                  downloadUrl = 'https://github.com/samzong/hf-model-downloader/releases/latest/download/hf-model-downloader-x86_64.dmg';
                }
              } else if (platform.includes('win')) {
                // Windows
                downloadUrl = 'https://github.com/samzong/hf-model-downloader/releases/latest/download/hf-model-downloader-windows-x86_64.zip';
              } else {
                // other
                window.open('https://github.com/samzong/hf-model-downloader/releases/latest', '_blank');
                return;
              }
              
              window.location.href = downloadUrl;
            }
            </script>
          EOF

      - run: npm install idoc@1 -g
      - run: idoc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
