name: Semantic Release

permissions:
  contents: write
  id-token: write

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: macos-latest
    outputs:
      released: ${{ steps.release.outputs.released }}
      version: ${{ steps.release.outputs.version }}
      tag: ${{ steps.release.outputs.tag }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN || github.token }}
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release dmgbuild
          pip install -r requirements.txt
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Python Semantic Release
        id: release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN || github.token }}
        run: |
          semantic-release version --print
          semantic-release publish
  
  update-homebrew:
    needs: release
    if: needs.release.outputs.released == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN || github.token }}
      
      - name: Update Homebrew Cask
        env:
          GH_PAT: ${{ secrets.GH_TOKEN || github.token }}
          VERSION: ${{ needs.release.outputs.version }}
        run: |
          echo "Updating Homebrew for version: $VERSION"
          make update-homebrew
            